### ISSUE TITLE
add proper post embed for Pleroma links

### ISSUE THREAD

**Issue by Soundtoxin** [olagood/drastikbot#2]
Currently it just prints "Pleroma" and none of the post text.
```
20:11:42 <@bard> https://weeaboo.space/notice/9nAGDZqg2EmXeYezOS
20:11:45 <@drastikbot> Pleroma
```

Some sites to test with to make sure it works for them all:
https://pleroma.site/
https://weeaboo.space/
https://welovela.in/
https://kawen.space/

Same example post viewed from two different instances:
https://weeaboo.space/notice/9nAGmwS1zX6rtAzlwW
https://pleroma.site/notice/9nAGmmjJbmc3bc1izI

**Comment by olagood** [comment]
This functionality has been added to the [url.py](https://github.com/olagood/drastikbot_modules/blob/master/url.py) module. The updated version will be pushed in a few moments.
